# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CryptoRSA.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmrsa(object):
    def setupUi(self, frmrsa):
        frmrsa.setObjectName("frmrsa")
        frmrsa.resize(1300, 600)
        frmrsa.setMinimumSize(QtCore.QSize(1300, 600))
        frmrsa.setMaximumSize(QtCore.QSize(1300, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("files/privacy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmrsa.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(frmrsa)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 371, 581))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.setFont(font)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setIconSize(QtCore.QSize(45, 45))
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")

        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("files/generales.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon1)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        item_1.setFont(0, font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("files/key.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon2)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(10)
        item_1.setFont(0, font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("files/info.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_1.setIcon(0, icon3)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("files/Encriptado.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon4)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("files/Desencriptado.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon5)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.tabpanel = QtWidgets.QTabWidget(self.centralwidget)
        self.tabpanel.setEnabled(True)
        self.tabpanel.setGeometry(QtCore.QRect(390, 10, 901, 581))
        self.tabpanel.setStyleSheet("QTabWidget::tab::disabled {width: 0; height: 0; margin: 0; padding: 0; border: none;} ")
        self.tabpanel.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabpanel.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabpanel.setElideMode(QtCore.Qt.ElideNone)
        self.tabpanel.setUsesScrollButtons(True)
        self.tabpanel.setDocumentMode(False)
        self.tabpanel.setTabsClosable(False)
        self.tabpanel.setMovable(False)
        self.tabpanel.setTabBarAutoHide(False)
        self.tabpanel.setObjectName("tabpanel")
        self.tabgenera_llave = QtWidgets.QWidget()
        self.tabgenera_llave.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabgenera_llave.setFont(font)
        self.tabgenera_llave.setStyleSheet("")
        self.tabgenera_llave.setObjectName("tabgenera_llave")
        self.tabpanel.addTab(self.tabgenera_llave, "")
        self.tab_about_us = QtWidgets.QWidget()
        self.tab_about_us.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_about_us.setFont(font)
        self.tab_about_us.setStyleSheet("")
        self.tab_about_us.setObjectName("tab_about_us")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_about_us)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 881, 541))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabpanel.addTab(self.tab_about_us, "")
        self.tabEncriptado = QtWidgets.QWidget()
        self.tabEncriptado.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabEncriptado.setFont(font)
        self.tabEncriptado.setStyleSheet("")
        self.tabEncriptado.setObjectName("tabEncriptado")
        self.tabpanel.addTab(self.tabEncriptado, "")
        self.tabDesencriptado = QtWidgets.QWidget()
        self.tabDesencriptado.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabDesencriptado.setFont(font)
        self.tabDesencriptado.setStyleSheet("")
        self.tabDesencriptado.setObjectName("tabDesencriptado")
        self.tabpanel.addTab(self.tabDesencriptado, "")
        frmrsa.setCentralWidget(self.centralwidget)
        self.actionGenerar_Llaves = QtWidgets.QAction(frmrsa)
        self.actionGenerar_Llaves.setObjectName("actionGenerar_Llaves")

        self.retranslateUi(frmrsa)
        self.tabpanel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmrsa)

    def retranslateUi(self, frmrsa):
        _translate = QtCore.QCoreApplication.translate
        frmrsa.setWindowTitle(_translate("frmrsa", "CryptoRSA"))
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.headerItem().setText(0, _translate("frmrsa", "1. Opciones"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("frmrsa", "Generales"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("frmrsa", "Generación de Llaves"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("frmrsa", "Acerca del Programa"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("frmrsa", "Encriptado"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("frmrsa", "Desencriptado"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabpanel.setTabText(self.tabpanel.indexOf(self.tabgenera_llave), _translate("frmrsa", "Genera Llaves"))
        self.plainTextEdit.setPlainText(_translate("frmrsa", "Encriptado y Desencriptado de archivos .txt basado en la criptografía RSA, utilizando una clave pública y privada.\n"
"\n"
"El programa facilita la generación y exportación de la clave publica y privada que es utilizada para la encriptación y desencriptación del archivo.\n"
"\n"
"Opciones:\n"
"     \n"
"     Generales\n"
"          Generación de Llaves: Opción para generar la llave Pública y Privada\n"
"          Acerca del Programa: Información general del programa\n"
"\n"
"     Encriptado: Opción donde se seleccionara la llave para \n"
"     encriptado y el archivo a encriptar\n"
"\n"
"     Desencriptado: Opción donde se seleccionara la llave para la \n"
"     desencriptación y el archivo .txt a desencriptar.\n"
"\n"
"---\n"
"Pablo Sao - 11540\n"
"Mirka Monzón - 18130"))
        self.tabpanel.setTabText(self.tabpanel.indexOf(self.tab_about_us), _translate("frmrsa", "Acerca del Programa"))
        self.tabpanel.setTabText(self.tabpanel.indexOf(self.tabEncriptado), _translate("frmrsa", "Encriptado"))
        self.tabpanel.setTabText(self.tabpanel.indexOf(self.tabDesencriptado), _translate("frmrsa", "Desencriptado"))
        self.actionGenerar_Llaves.setText(_translate("frmrsa", "Generar Llaves"))
        self.treeWidget.expandAll()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmrsa = QtWidgets.QMainWindow()
    ui = Ui_frmrsa()
    ui.setupUi(frmrsa)
    frmrsa.show()
    sys.exit(app.exec_())
